spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/user.sql
        - classpath:sql/restraurant.sql

logging:
  level:
    com.example.mywas: DEBUG
    org:
      springframework:
        jdbc:
          datasource: DEBUG
      hibernate:
        SQL: DEBUG


# sql.user.save 회원가입
sql:
  user:
    save: 'INSERT INTO users (username, email, password, role) VALUES (?, ?, ?, ?)'
    findAll: 'select * from users'
    findUserByUserName: 'select * from users where username = ?'
    findUserByUserId: 'SELECT * FROM users where userid = ?'
    findUserByUserNameAndRole: 'select * from users where username = ? and role = ?'

# sql.restaurant.save 사용자 식당 등록
  restaurant:
    save: 'INSERT INTO restaurant (user_id, name, address, description) VALUES (?, ?, ?, ?)' # 식당 등록
    findAll: 'select * from restaurant' # 현재 서버에 등록된 전체 식당
    findRestaurantByUserId: 'SELECT * FROM restaurant where user_id = ?' # 사용자가 등록한 식당들 리스트 목록