spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/user.sql

logging:
  level:
    com.example.mywas: DEBUG
    org:
      springframework:
        jdbc:
          datasource: DEBUG
      hibernate:
        SQL: DEBUG


# sql.user.save 회원가입
sql:
  user:
    save: 'INSERT INTO users (username, email, password, role) VALUES (?, ?, ?, ?)'
    findAll: 'select * from users'
    findUserByUserName: 'select * from users where username = ?'
    findUserByUserNameAndRole: 'select * from users where username = ? and role = ?'




